steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -f
      - deploy/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/driftwatch:$COMMIT_SHA
      - -t
      - gcr.io/$PROJECT_ID/driftwatch:latest
      - .

  - name: "gcr.io/cloud-builders/docker"
    args: [push, gcr.io/$PROJECT_ID/driftwatch:$COMMIT_SHA]

  - name: "gcr.io/cloud-builders/docker"
    args: [push, gcr.io/$PROJECT_ID/driftwatch:latest]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - driftwatch-daily
      - --image=gcr.io/$PROJECT_ID/driftwatch:$COMMIT_SHA
      - --region=us-central1

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - run
      - jobs
      - update
      - driftwatch-profile
      - --image=gcr.io/$PROJECT_ID/driftwatch:$COMMIT_SHA
      - --region=us-central1

images:
  - gcr.io/$PROJECT_ID/driftwatch:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/driftwatch:latest
